#!/bin/bash

if [ "${LL_DUMP_BYTECODE}" != "" ]; then
    JVM_OPTION="${JVM_OPTION} -DdumpByteCode=on"
fi

if [ "${LL_DUMP_PATTERN}" != "" ]; then
    JVM_OPTION="${JVM_OPTION} -DdumpPattern=on"
fi

java $JVM_OPTION -jar ./target/loglang-1.0-SNAPSHOT-jar-with-dependencies.jar $@
