#!/bin/bash

if [ "${LL_DUMP_BYTECODE}" != "" ]; then
    JVM_OPTION="${JVM_OPTION} -DdumpByteCode=on"
fi

if [ "${LL_DUMP_PATTERN}" != "" ]; then
    JVM_OPTION="${JVM_OPTION} -DdumpPattern=on"
fi

if [ "${LL_PEG_ONLY}" != "" ]; then
    JVM_OPTION="${JVM_OPTION} -DpegOnly=on"
fi

if [ "${LL_DUMP_PEG}" != "" ]; then
    JVM_OPTION="${JVM_OPTION} -DdumpPEG=on"
fi

if [ "${LL_DUMP_TYPED_PEG}" != "" ]; then
    JVM_OPTION="${JVM_OPTION} -DdumpTypedPEG=on"
fi


java $JVM_OPTION -jar ./target/loglang-1.0-SNAPSHOT-jar-with-dependencies.jar $@
